---
- hosts: slurmservers
  become: true
  roles:
    - galaxyproject.repos
    - galaxyproject.slurm
  post_tasks:
    - name: Install BWA
      become: true
      apt:
        package: bwa
        state: present
    - name: Copy run_bwa script
      copy:
        src: run_bwa.sh
        dest: /home/ubuntu/run_bwa.sh
    - name: build BWA index
      command:
        cmd: bwa index MN908947_3_Wuhan-Hu-1.fasta
        creates: MN908947_3_Wuhan-Hu-1.fasta.bwt

